// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace OnlineGroceryApps.Models;

public partial class Admin
{
    public int AdminId { get; set; }


    [Required(ErrorMessage = "Email is required")]
    [EmailAddress(ErrorMessage = "Invalid email format")]

    public string AdminEmail { get; set; }

    [Required(ErrorMessage = "Password is required")]
    [DataType(DataType.Password)]
    [NotMapped]
    public string NormPassword { get; set; }
    public byte[] AdminPassword { get; set; }

    [Required(ErrorMessage = "Admin Name is required")]
    public string AdminName { get; set; }

    [Phone(ErrorMessage = "Invalid phone number format")]
    public string AdminPhoneno { get; set; }
}