// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineGroceryApps.Models;

public partial class Fnbcbank
{
    public int AccountId { get; set; }

    public int AccountNumber { get; set; }

    public int Balance { get; set; }

    public int? UserId { get; set; }

    public virtual User User { get; set; }
}