// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineGroceryApps.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int ProductPrice { get; set; }

    public int ProductStocks { get; set; }

    public string ProductImage { get; set; }

    public int? CategoryId { get; set; }

    public string ProductDescription { get; set; }

    public int? BrandId { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<Cartitem> Cartitems { get; set; } = new List<Cartitem>();

    public virtual Category Category { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}